### ISSUE TITLE
How to allow escape characters \n in secret env variable using docker.env?

### ISSUE THREAD

**Issue by diavrank** [quavedev/apple-oauth#14]
Hello, I am using Apple OAuth for my **Meteor** app and **React Native**, and it is already **working well**. However, I faced only a problem during this process and it was related to the **content of the secret environment variable**. I use **docker** to deploy my app, so, I configure the env variables in a **docker.env** file, thus, I pasted the value of my secret as README says (with **\n** characters), however, when the app starts, the secret is stored in the database with **double slash** (**\\n**) instead of one slash (as I defined in docker.env).

I was figuring out how to fix it, but I haven't found a good solution, so, I had to modify the content directly from the database, and then it worked the OAuth with Apple. So, I was wondering if any can help me with this to avoid update it in each deployment?

**Comment by renanccastro** [comment]
Are you using docker compose?
If so, you can set the env var inside the yaml file, like so:

```yaml
myservice:
  build: .
  env_file:
    # Files in this array have the same format as `.env` files, but they are
    # passed to container's environment instead being used inside this
    # `docker-compose.yml` file
    - variables.env
  environment:
    SSH_KEY: >
      --------- WHATEVER ----------
      randomkeybase64thingforyourse
      rvice
      ------- END WHATEVER --------
```
